### ISSUE TITLE
Two unrelated files present in project when installing with 'npx create-r3f-app next'

### ISSUE THREAD

**Issue by X-Equals-Zero** [pmndrs/react-three-next#100]
After setting up the project, there are two files called 'sw.js' and 'workbox-6a1bf588.js' in the /public folder.

I've never had such files in next projects, nor are they in the repository, so I am curious what they are for?

[sw.txt](https://github.com/pmndrs/react-three-next/files/9804588/sw.txt)
[workbox-6a1bf588.txt](https://github.com/pmndrs/react-three-next/files/9804589/workbox-6a1bf588.txt)

**Comment by pi43r** [comment]
I assume these are from the https://github.com/shadowwalker/next-pwa package.
They allow users to install the app and use it offline. More on service workers here: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

and workbox: https://web.dev/workbox/
