### ISSUE TITLE
ScrollControls from react-three/drei not working with Canvas

### ISSUE THREAD

**Issue by gene-ius** [pmndrs/react-three-next#101]
Hello! I have been using this starter to create a web app that needs to use orbit controls for some pages but **toggles to use scroll controls on other pages**. I have noted how orbit controls are implemented with the `<LControl/>`  component in `canvas.jsx` and pointer events are connected to the `dom` stored in global state.  

However, trying to use `react-three/drei`'s helper , `<ScrollControls>` ([link to ScrollControl docs](https://github.com/pmndrs/drei#scrollcontrols)) within a page file has been unsuccessful. Pointer and scroll events seem to be dropped entirely and I have been left with an unresponsive screen after disabling the default orbit controls. As of now, I have tried connecting the dom in the global state to the `<ScrollControls>` helper and implemented a controls object similar to `<LControl/>` - that returns a `<ScrollControls>` object instead of Orbit -  but still all of my pointer events are not registering. Is there any way to reconfigure the canvas so that this scroll navigation helper can be used? Again, I hope to toggle between, scroll and orbit controls based on the page the client is on and anticipate using global state to do so. I appreciate any assistance with this as I've been stuck for almost 2 weeks now unfortunately :(

**Comment by GabeDahl** [comment]
I'm having the same issue. My last resort is to create an entirely separate R3F Canvas in the page's JSX instead of adding canvas elements to the Page.canvas property.

**Comment by gene-ius** [comment]
Perfect thank you for the help @GabeDahl ! It looks like my created app is a couple commits behind the addition of the templates folder, so I will be migrating all my changes to the new react-three-next starter. I was able to find a hacky workaround with global state, and dreis `ScrollControls` helper but this approach is much cleaner in my opinion and hopefully would cause less reloads than my scroll controls toggle.

Along those lines , just a quick follow up. Would I be able to enable and disable scroll controls for specific pages with the `Scroll.tsx` component? I need orbit controls for my `index.tsx` page , but would require a scrollable canvas and dom for other pages. Im wondering how I would do this , and if a global state would be ideal in toggling the use of this utility?

**Comment by GabeDahl** [comment]
> Would I be able to enable and disable scroll controls for specific pages with the `Scroll.tsx` component?
Yeah, I made a little context above the scroll wrapper & canvas that has a simple `pages` value.
```
import { Dispatch, ReactNode, SetStateAction, createContext, useState } from 'react'

interface ScrollContextState {
  pages: number
  setPages: Dispatch<SetStateAction<number>>
}

export const ScrollContext = createContext<ScrollContextState>(null)

export const ScrollContextProvider = ({ children }: { children: ReactNode }) => {
  const [pages, setPages] = useState(1)
  return <ScrollContext.Provider value={{ pages, setPages }}>{children}</ScrollContext.Provider>
}
```

Then I set the pages in each route/page component
```
  useEffect(() => {
    setPages(3)
  }, [])
```
or
```
  useEffect(() => {
    setPages(1)
  }, [])
```

I'm currently working on a way to RELIABLY reset the camera position & scroll position/state upon route change, but it's too wonky error-prone right now

**Comment by LuLue7775** [comment]
@gene-ius @GabeDahl Thank you for your input!
I'm facing the same issue while I was trying to use independent ScrollControls for individual pages. And somehow ScrollControls only works on top level (in _app.jsx), whereas not working in child component. Still figuring out why.

And based on discussion above,
does it mean I'll have to use Scroll template along with @studio-freight/lenis, instead of dreis ScrollControls helper?

Still really confused. If anyone can point out the right direction I'll be really appreciate it!

**Comment by RenaudRohlinger** [comment]
Native scroll should be supported OOTB, will investigate for a better implementation with lenis in the near future.
