### ISSUE TITLE
Any luck with next 13?

### ISSUE THREAD

**Issue by nwpointer** [pmndrs/react-three-next#103]
Tried using next 13 and the new layout RFC but ran into some weird compilation errors - mostly just curious if anyone else had this issue and if/when this project plans on moving to the new format

**Comment by RenaudRohlinger** [comment]
Hi,

I just tried to implement layout RFC but I do find the implementation stage a little too early at this moment. It would be necessary to have a custom Template system to mix properly dom and canvas, or maybe we could tag each child with an `r3f` property (which was the trick used in the first version of this starter). Also right now it's not possible anymore to use the `Component.canvas(pageProps)` syntax which is troublesome.

**Comment by nwpointer** [comment]
Checks out, will stay tuned.

**Comment by tomimarkus991** [comment]
i tried to use r3f with next 13 (in my own project). Everything was working until build step, where it got stuck generating static pages
