### ISSUE TITLE
Styled Components r3f Next13 unexpected behavior

### ISSUE THREAD

**Issue by mholovko** [pmndrs/react-three-next#104]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/10801935/199555721-604cdc9d-3bc5-483c-a0a3-08c1dd3262f0.png">

Unstyled elements after page reload, using styled components template.

**Comment by RenaudRohlinger** [comment]
Hello!

When using styled-components with nextjs it is necessary to inform the compiler in the `next.config.js` file.
```
// uncomment the following snippet if using styled-components
// compiler: {
//   styledComponents: true,
// },
```
I will let this issue open until I automatized this in the [create-r3f-app starter](https://github.com/utsuboco/create-r3f-app).

**Comment by RenaudRohlinger** [comment]
https://github.com/utsuboco/create-r3f-app/commit/2a12912b8630a103ab674e74adcf44d6d003c0c3 install the config automatically now 👍
