### ISSUE TITLE
Can't scroll a div. Canvas gets event instead

### ISSUE THREAD

**Issue by MatthewGreenberg** [pmndrs/react-three-next#111]
Check out this gif https://media.giphy.com/media/Jxj9BOgb4MoyYlw9Ot/giphy.gif
I can't figure out how to scroll a scrollable div. It seems as though all of the mouse wheel  events get sucked up by the canvas. Any idea how to get around that?

**Comment by LuLue7775** [comment]
Same here. And it's causing useScroll (@react-three/drei) undefined in child. Any solution to set scroll properly?

**Comment by RenaudRohlinger** [comment]
new release adds OOTB scroll sync.
