### ISSUE TITLE
Error when installing styled-components template

### ISSUE THREAD

**Issue by billyberkouwer** [pmndrs/react-three-next#113]
When I run command `yarn create r3f-app next my-app styled -ts` packages do not install and I receive the following error:

> Error! yarn installation failed 

> Initializing for styled-components...

node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module 'tailwindcss'
Require stack:
- **************\next-three-styled-2\noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports **************AppData\Local\Yarn\Data\global\node_modules\import-from\index.js:5:100)
    at compilePostCss **************AppData\Local\Yarn\Data\global\node_modules\create-r3f-app\lib\stacks\next.js:147:23)
    at migrateTailwindToStyled **************AppData\Local\Yarn\Data\global\node_modules\create-r3f-app\lib\stacks\next.js:158:26)
    at async initForStyledComponents **************AppData\Local\Yarn\Data\global\node_modules\create-r3f-app\lib\stacks\next.js:275:3)       
    at async next **************AppData\Local\Yarn\Data\global\node_modules\create-r3f-app\lib\stacks\next.js:329:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '***************\\next-three-styled-2\\noop.js'
  ]
}

Node.js v18.2.0
error Command failed.
Exit code: 1
Command: *********\Yarn\bin\create-r3f-app
Arguments: next next-three-styled-2 styled
Directory: ************
Output:

**Comment by RenaudRohlinger** [comment]
Thanks for the issue! This should be fixed:
https://github.com/utsuboco/create-r3f-app/commit/b2c939defcecbb2bdb5390807026e4dadc9772c7

**Comment by billyberkouwer** [comment]
Thanks a lot @RenaudRohlinger!
