### ISSUE TITLE
Hydration error

### ISSUE THREAD

**Issue by marchitecht** [pmndrs/react-three-next#121]
Hello!

Is there anyone knows how to fix this hydration error?

I tried already both static and dynamic imports. 

What am I doing wrong?
![image](https://user-images.githubusercontent.com/90207733/230083780-cbf1503e-9b64-4f1e-a6df-a437be216be2.png)

**Comment by netgfx** [comment]
You are probably trying to change something at runtime, which results in being different from what the server of nextjs pre-compiled. Usually to avoid this (apart from relying on SSR (server side rendering) only for displaying the content)
Is to make any modifications inside a useEffect (SSR doesn't validate code inside useEffect)
Or you can try to conditionally render values whether or not the DOM `window` exists (on SSR there is no window or document).

If the above don't make much sense, try to do some look up on how SSR works and specifically NextJS (their documentation is pretty ok)
