### ISSUE TITLE
Error when running styled-components template

### ISSUE THREAD

**Issue by hatchli** [pmndrs/react-three-next#129]
When performing clean install with `styled-components`,  via `yarn create r3f-app next test5 styled`
Installation goes fine (though regardless of whether -ts is provided or not, the following occurs:
```
> Success! Installed dependencies for styled-components 

> Initializing for styled-components... 

> Downgraded to @types/react@17.0.43 in order to fix styled-components (see DefinitelyTyped/issues/59765) 
```

On `yarn run dev ` receive error:
```
wait  - compiling /_error (client and server)...
error - ./src/components/dom/Layout.jsx:2:0
Module not found: Empty dependency (no request)
  1 | 'use client'
> 2 | import {} from ''
  3 | 
  4 | import { useRef } from 'react'
  5 | import dynamic from 'next/dynamic'
```

Looking at the file, besides the aforementioned `import {} from ''`, there is no difference between this file and the tailwind generated (default) version [which does work].

Deleting the failed import results in the project building, but not correctly and no assets loading and no styling being applied.

Following the solution provided at #125 only works if `styled` is omitted. 

Node version `v16.19.1`, `macOS 13.3.1`

**Comment by 19Sean96** [comment]
experiencing the same issue.

**Comment by RenaudRohlinger** [comment]
Thanks for the report, latest version of create-r3f-app should fix this issue.
