### ISSUE TITLE
Install command with -ts result to "node version incompatible" error

### ISSUE THREAD

**Issue by atzmael** [pmndrs/react-three-next#135]
Hi
I'm trying to install the project with `yarn create r3f-app next my-app -ts`
When I first use it, the `create-r3f-app` and cloning works well, but then it runs into an error : 
```
Command failed with exit code 1: yarn install
error next@13.4.3: The engine "node" is incompatible with this module. Expected version ">=16.8.0". Got "14.19.1"
```

So I use nvm to switch to 16.8.0
But then it runs into this error : 
```
yarn create r3f-app next test -ts
yarn create v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error create-strapi-app@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "20.1.0"
error Found incompatible module.
```

I really don't know how to fix this !

**Comment by yct37785** [comment]
Are you able to use the LTS version of node instead? `18.16.0`. This is my version of node and running `yarn create r3f-app next my-app -ts` and then `yarn run dev` on my-app works.

**Comment by atzmael** [comment]
Well, I followed the resolution of the issue on vercel, it was the package strapi strangely installed globally, so I removed it works well. Thanks @yct37785 !
