### ISSUE TITLE
Minimal Starter

### ISSUE THREAD

**Issue by dustinlacewell** [pmndrs/react-three-next#27]
This is just some feedback, feel free to close it.

The current starter, while very pretty while running, is quite complex for a starter. There is substantial infrastructure in place for implementing the current example demo swapping logic.

In another issue I heard that typescript was avoided to keep the starter as accessible as possible. I think the way the current "starter" basically implements a featured example showcase site is contradictory to that.

What I'm looking for in a "react-three-next" starter is the minimal amount of code to demonstrate _how_ to integrate react-three with next since next's SSR doesn't make that straightforward. The starter should be illuminating that bit. It should be assumed that I can take it from there. I think the current code is better as a more sophisticated example project.

As it stands, I'm spending a bunch of time figuring out exactly how and what I can delete from the current starter to actually start what I'm trying to work on.

I really do like the code and the site is beautiful but I just feel it's counter to the spirit of a starter.

**Comment by RenaudRohlinger** [comment]
@dustinlacewell Thanks for the feedback. I agree on this one, as soon as I fixed all the issues with the latest release of threejs r128 I will lighten up the starter

**Comment by RenaudRohlinger** [comment]
@dustinlacewell the new release should now be better! https://react-three-next-git-main-pmndrs.vercel.app/
