### ISSUE TITLE
Styling on the Dom class prevents the pointer events on the r3f canvas

### ISSUE THREAD

**Issue by miklosme** [pmndrs/react-three-next#4]
`OrbitControls` does not work out of the box, because the `Dom` components uses the full screen, so pointer events does not reach the canvas. I fixed this in my project by removing the `bottom-0` class. I feel like this is a dirty hack, otherwise would send a PR.

**Comment by RenaudRohlinger** [comment]
Thanks! I temporarily added your fix while trying to figure out a cleaner way to do it.
