### ISSUE TITLE
question: zustand middleware

### ISSUE THREAD

**Issue by njm222** [pmndrs/react-three-next#41]
Hello,

I tried to persist the store's data with this middleware solution: https://github.com/pmndrs/zustand#persist-middleware

but I get a `Converting circular structure to JSON` error in every `useEffect` that sets the state

**Does anyone know why this is happening?**

_From the past merged PRs in zustand it seems like this was worked on recently_

Here is an example stack trace:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactFiber$7h6sih73en9' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at stringify (<anonymous>)
    at eval (middleware.js?926f:87)
    at setItem (middleware.js?926f:146)
    at Function.api.setState (middleware.js?926f:157)
    at eval (_app.jsx?434a:51
```

**Comment by guidovizoso** [comment]
If you're trying to persist the store that has the DOM and Router I believe it's impossible. The DOM has references to parents and children that cannot be converted to JSON.
Maybe one of the creators/mantainers can give you a more detailed explanation or a solution but to store JSON it must be stripped of all references and relations.

**Comment by njm222** [comment]
Yes my store has the DOM & Router so the references and relations are definitely causing the issue. 
Thanks a lot for the insight, I will ask zustand maintainers before I dig into finding a solution.

**Comment by njm222** [comment]
Simple solutions:

- `whitelist` or `blacklist` store keys in the persist config
- overwrite the `serialize` & `deserialize` functions in the config
