### ISSUE TITLE
texture not loading

### ISSUE THREAD

**Issue by amir-al-razin** [pmndrs/react-three-next#45]
# screen becomes white when using any texture loader i.e useTexture,useLoader 

![prob1](https://user-images.githubusercontent.com/82754350/126190116-7ee5bc9f-992a-4092-94fa-c727e894f0c7.png)

after uncommenting useTexture() hook

![prob2](https://user-images.githubusercontent.com/82754350/126190180-c462acd4-1fd5-40e5-aad0-ae2bab886708.png)

**Comment by njm222** [comment]
Are there any errors in the console?

Also I'm pretty sure you need to call that dynamic import outside of the component

_What extension are you using to get the package sizes?_

**Comment by RenaudRohlinger** [comment]
@amir-al-razin The way you are loading the texture is not correct. You don't need dynamic import or anything like that, it's already taking care of with Suspense in Drei.
Try putting your cloud.png texture in your public folder and then load it using ```const texture = useTexture('/cloud.png')``` instead

**Comment by amir-al-razin** [comment]
> @amir-al-razin The way you are loading the texture is not correct. You don't need dynamic import or anything like that, it's already taking care of with Suspense in Drei.
> Try putting your cloud.png texture in your public folder and then load it using `const texture = useTexture('/cloud.png')` instead

thanks it worked 😅
