### ISSUE TITLE
npx create-r3f-app [name] -ts creates jsx files 

### ISSUE THREAD

**Issue by milancr** [pmndrs/react-three-next#51]
![Screen Shot 2021-08-25 at 11 15 53 AM](https://user-images.githubusercontent.com/61572718/130817586-c86d7f00-f22b-48cc-b169-4be4cfaa8504.png)

![Screen Shot 2021-08-25 at 11 07 09 AM](https://user-images.githubusercontent.com/61572718/130817486-d480f41e-ab75-4f1a-b8f5-a1d0e9014c6d.png)

**Comment by RenaudRohlinger** [comment]
From my experience is must be because npm must try to do `npm next `(as we do with yarn next) instead of `npm run next`.

It should be fixable on create-r3f-app. Thanks!

**Comment by RenaudRohlinger** [comment]
I tried to reproduce the issue with the same parameters but everything runs fine. If anyone else can reproduce this issue please feel free to bump this issue and I will investigate more.

![image](https://user-images.githubusercontent.com/15867665/132087472-1226aa28-8ca4-40e0-90c9-1352cab6bf8f.png)
