### ISSUE TITLE
ERR_REQUIRE_ESM when trying to use @react-three/xr with react-three-next

### ISSUE THREAD

**Issue by pfortes** [pmndrs/react-three-next#53]
I am trying to add VR functionality to a project that uses react-three-next.

Just trying to import the VRCanvas with the line:

`import { VRCanvas } from '@react-three/xr'
`

Fails with the error: ERR_REQUIRE_ESM
Must use import to load ES Module: /.../app/node_modules/three/examples/jsm/loaders/GLTFLoader.js

I tried using **next-transpile-modules** to load @react-three/xr but it didn't work.
And also tried using the new next.js **experimental ESM feature** ( { esmExternals: "loose" } ) in next.config.js without success.

Am i missing something?
Is this a problem with how react-three/xr is built? 

Does anyone has an idea on how to make them work?

Thanks

**Comment by CodyJasonBennett** [comment]
You'll have to transpile `three` instead.

**Comment by pfortes** [comment]
I tried transpiling three and xr and it is not working either

`const withTM = require('next-transpile-modules')(['three', '@react-three/xr'])`

![Screen Shot 2021-09-01 at 7 00 49 PM](https://user-images.githubusercontent.com/782464/131760828-18b96565-4db4-411c-a2d7-9f998f891670.png)


on the other hand, i don't unnderstand how could i use three-stdlib because the code that is failing is inside react-three/xr 

Tnx

**Comment by CodyJasonBennett** [comment]
I see, they must have dropped `three-stdlib` and this is indeed an issue with `@react-three/xr`. I'll forward this over there and take a closer look.

Out of curiousity, are you able to transpile examples as well? Something like:

```js
const withTM = require('next-transpile-modules')(['three', 'three/examples/jsm/loaders/GLTFLoader', '@react-three/xr'])
```

**Comment by pfortes** [comment]
I have tried to transpile the example but i keep getting an error.

What i noticed is that including @react-three/xr in the next-transpile-module brakes on the build stage, giving a slightly diferent error:
![transpileAll3](https://user-images.githubusercontent.com/782464/132074360-20e0742d-1504-4bd0-88d6-9d4c2e8eac72.png)

When i dont transpile anything or i transpile 'three' and 'three/examples/jsm/loaders/GLTFLoader' i get the error:
![transpileThreeAndGldfLoader](https://user-images.githubusercontent.com/782464/132074342-bb18c2ba-5ca5-4ba9-a429-52ce757a22eb.png)

i will try to make a reproduction in a codesandbox so it is easier to test

Thank you

**Comment by pfortes** [comment]
I have created a minimal reproduction, it's the react-three-next starter with the changes from this commit:
https://github.com/pfortes/r3f-next-xr/commit/941d16e5ffd2f39463b095186c2f43805f591757
- install @react-three/xr and next-transpile-modules
- import VRCanvas in canvas.jsx
- try to transpile the modules in next.config.js

There is a codesandbox at:
https://codesandbox.io/s/optimistic-lamport-27d52

And the code can be found at:
https://github.com/pfortes/r3f-next-xr

I hope this helps to visualize the situation better, maybe i am just doing something wrong on the transpiling stage 🤒 

Tnx

**Comment by CodyJasonBennett** [comment]
It seems that this issue came up with the introduction of https://github.com/mrdoob/three.js/pull/21838.

**Comment by pfortes** [comment]
🌴  Success! 😄  

I have managed to make it work!

it was a combination between activating the experimental esmExternals (i think this helps us with the Type: module thing) and correctly transpiling @react-three/xr and @webxr-input-profiles/motion-controllers
 
You can see the changes in https://github.com/pfortes/r3f-next-xr/commit/60db7ea9980f195ef3f32bee1e1991878c13ce09

And an updated sandbox at:
https://codesandbox.io/s/optimistic-lamport-27d52?file=/next.config.js

Thanks for the help and motivation!

**Comment by CodyJasonBennett** [comment]
This has been resolved in https://github.com/pmndrs/react-xr/issues/101.
