### ISSUE TITLE
Can't install `npx create-r3f-app next my-app` error 

### ISSUE THREAD

**Issue by Johnathan-Aretos** [pmndrs/react-three-next#55]
I'm trying to install the starter, I'm running `npx create-r3f-app next my-app -ts`

and receiving the error 

```
    appStyle = style ?? 'tailwind';
                      ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

I'm running npm `7.22.0`

Anyone else facing this issue?

**Comment by CodyJasonBennett** [comment]
Nullish coalescing was added in Node v14. Maybe we need to bump `engines` to reflect?

**Comment by Johnathan-Aretos** [comment]
Can confirm, upgrading did fix the issue. Thanks. 

What do you mean by bump `engines`?

**Comment by CodyJasonBennett** [comment]
It's a key that we put in package.json to let people on older versions know of possible incompatibility.

**Comment by RenaudRohlinger** [comment]
@CodyJasonBennett Thank you very much for the help! And thanks for the fix @Johnathan-Aretos!

Happy it is solved 😄
