### ISSUE TITLE
Intall gets an error

### ISSUE THREAD

**Issue by yogesh2503** [pmndrs/react-three-next#57]
Hi ,
When I try to install I will get an error. 
yogesh@yogi:~/Dev$ yarn create r3f-app next my-app -ts
yarn create v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-r3f-app > jscodeshift@0.13.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] Building fresh packages...
success Installed "create-r3f-app@1.4.1" with binaries:
      - create-r3f-app
[####################################################################################################################################################################################################] 347/347/home/yogesh/.config/yarn/global/node_modules/create-r3f-app/bin/create-r3f-app:22
    appStyle = style ?? 'tailwind';
                      ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed.
Exit code: 1
Command: /home/yogesh/.yarn/bin/create-r3f-app
Arguments: next my-app -ts
Directory: /home/yogesh/Dev
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command. 
[read.md](https://github.com/pmndrs/react-three-next/files/7158833/read.md)

[read.md](https://github.com/pmndrs/react-three-next/files/7158834/read.md)

**Comment by CodyJasonBennett** [comment]
See #55. It seems you're on an older version of Node.

**Comment by Johnathan-Aretos** [comment]
I would have thought `engines` would have given a better error. In relation to the PR @CodyJasonBennett mentioned.

**Comment by omarryhan** [comment]
@CodyJasonBennett is right

summary of how I fixed it:

1. Install NVM if not already installed

```sh
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
```

2. Switch to atleast v14 (I was on v12)

```
nvm use 14
````
