### ISSUE TITLE
Render issue with multiple shaderMaterial

### ISSUE THREAD

**Issue by chwan1** [pmndrs/react-three-next#65]
Using multiple shaderMaterial seems to have an error.

I initialized a project with `yarn create r3f-app next my-app styled -ts` and everything seems working fine.
But when I duplicate the Shader folder and name the corresponding fields (Shader -> Shader2, ColorShiftMaterial -> ColorShiftMaterial2) and add the component to index.jsx, the second material turns white.

Seems that the material is not initialized properly, because `meshRef.current.material.uniforms` turn out to be `undefined`.

![image](https://user-images.githubusercontent.com/5978145/145673555-703ef4ee-eb41-443b-a2b5-798ad7b89837.png)

**Comment by RenaudRohlinger** [comment]
It should work out of the box. I would need a minimum repro to better understand the issue. Feel free to re-open if the issue persists with an example and I will check it out.
