### ISSUE TITLE
proposal: provide a branch without Webpack dependency

### ISSUE THREAD

**Issue by hilalisa67** [pmndrs/react-three-next#66]
Hi,
Thx you for sharing
Could you provide a branch without Webpack dependency

**Comment by gsimone** [comment]
What's the idea here? Webpack is a next.js dependency, it's only a dep here because of some overrides. Do you want a version without overrides or somehow a version without webpack?

**Comment by hilalisa67** [comment]
Yes I would like to have a version without webpack

**Comment by RenaudRohlinger** [comment]
Hi!
Actually, nextjs does not require webpack as a dependency, it was used in some previous versions but it might be possible to remove it. I will see if anything breaks

**Comment by RenaudRohlinger** [comment]
Webpack has been removed from the dependencies @hilalisa67
