### ISSUE TITLE
Issue running yarn create r3f-app

### ISSUE THREAD

**Issue by cachemoney** [pmndrs/react-three-next#67]
I have node v16.3.1, yarn: v1.22.17 installed an tried running the command below
`yarn create r3f-app next next-remotion styled -ts node`
and get error below.  Any ideas I can try to resolve this?  Thanks!
I 
![Screen Shot 2022-01-15 at 12 41 49 PM](https://user-images.githubusercontent.com/477635/149634071-78918653-b71c-43eb-a333-8c156f88d775.png)

**Comment by GmBodhi** [comment]
Same error here!

**Comment by Toseben** [comment]
Encountered the same error just now! My `.babelrc` plugins looked like this and the solution for the above error was to remove double `styled-components`.

```
"plugins": [
  "glsl",
  "styled-components",
  "styled-components"
]
```

**Comment by RenaudRohlinger** [comment]
Indeed! Thanks for the report it seems that I forgot to remove the default plugin styled-components https://github.com/utsuboco/sougen/blob/dev/.babelrc#L15 [despite the fact that the starter's cli injects it ](https://github.com/RenaudRohlinger/create-r3f-app/blob/639e76365dab297ecb6c1ebe16b029d45897a94f/lib/stacks/next.js#L251).

I will remove `styled-components` from `.babelrc` by default

**Comment by rohanrehman** [comment]
Still throws an error.

`yarn create r3f-app next my-app styled -ts node`



```
> Success! Installed dependencies for TypeScript

> Initializing for styled-components...

> Generating styled-components from tailwind

> Generating styled-components from tailwind

> Generating styled-components from tailwind

> Generating styled-components from tailwind

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/Users/r/GitHub/my-app/.babelrc'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/r/GitHub/my-app/.babelrc'
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-r3f-app
Arguments: next my-app styled -ts node
Directory: /Users/rohan/GitHub
Output:

```
