### ISSUE TITLE
Index is remounting

### ISSUE THREAD

**Issue by qwertypants** [pmndrs/react-three-next#68]
## Expected Behavior
The `/pages/index` should only mount once.

## Current Behavior
The top level `/pages/index` is mounting twice. This is causing `useEffect`'s that are meant to run once, run twice due to a remount.

## Steps to Reproduce
1. `yarn create r3f-app next doubleLoad`
2. `cd doubleLoad`
3. In `index.jsx`, add a `useEffect`, [example](https://github.com/qwertypants/double-load-issue/blob/1655ab6c70a1d1cd75747a13a47c5f77b3f78032/src/pages/index.jsx#L33-L35).
```
useEffect(() => {
    console.log('load')
  }, []);
```
4. Observe that console logs twice.

Repo example: https://github.com/qwertypants/double-load-issue
<img width="724" alt="Screen Shot 2022-01-15 at 1 47 17 PM" src="https://user-images.githubusercontent.com/206774/149634483-3f0a109e-1037-4eec-80d1-85044db1521a.png">

**Comment by PhiDung-hub** [comment]
Any solution yet for this issue?

**Comment by RenaudRohlinger** [comment]
Couldn't reproduce the issue but anyway the last version should solve the issue 👍
