### ISSUE TITLE
R3F components fall over if only pass one child component into "Page" component in <page>.tsx

### ISSUE THREAD

**Issue by midanosi** [pmndrs/react-three-next#70]
I tried starting off my codebase by cloning `/pages/box.tsx` and `/canvas/Box.tsx`. Let's say my new component is called "Shape". In `/pages/shape.tsx`, I changed the `Page` component to only have <R3F r3f/>, and not <DOM />.

This meant that at this line: https://github.com/pmndrs/react-three-next/blob/main/src/pages/_app.jsx#L37, the child.length > 1 check fails, and so renders the Component without wrapping it in LCanvas.

Is there a good reason for this `child.length > 1` check? If not, I suggest it's removed. Or mandate and document that all `/pages/<page>/tsx` files must provide at least one DOM and one R3F component, though this would be a weird requirement I think.

**Comment by emaLorenzo** [comment]
I've created a PR for this #73

**Comment by RenaudRohlinger** [comment]
Thanks 👍
