### ISSUE TITLE
How to use ScrollControls 

### ISSUE THREAD

**Issue by clearly-outsane** [pmndrs/react-three-next#72]
The DOM is outside the Canvas so I can't wrap it in ScrollControls. I'm not sure how to handle scrolling for the canvas and DOM otherwise? Do I just pass a scroll progress value to the canvas and update the camera as I scroll through the page?

**Comment by clearly-outsane** [comment]
Any thoughts whatsover? I'm curious to know if this is a valid question

**Comment by eriksachse** [comment]
You don't have to use DOM elements outside the Canvas. Just use ScrollControls with `<Scroll html>…</Scroll>`

**Comment by clearly-outsane** [comment]
Oh it's that simple huh- I thought you HAVE to use it outside or else something won't work as good

**Comment by eriksachse** [comment]
Yeah there are different ways of displaying text inside the scene. There is Jotai, drei/Html, drei/ScrollControls, and of course the good old png.

**Comment by gavan1** [comment]
when using it with next.js Is it better to import and use ScrollControlls in the **_app.jsx,** page.js or the canvas/component.jsx itself?
