### ISSUE TITLE
`yarn create r3f-app next my-app -ts` install error

### ISSUE THREAD

**Issue by jonrrivera** [pmndrs/react-three-next#75]
hey! thanks for the great codebase!

after running the `yarn create r3f-app next my-app -ts` command im getting this error. seems like we need to install `yarn add --dev @types/react` to be able to use typescript.

<img width="798" alt="Screen Shot 2022-04-15 at 11 06 54 AM" src="https://user-images.githubusercontent.com/18686388/163605695-0b9247ec-5004-4241-b57a-a9c5fbb75285.png">

please let me know if you need any clarification, thanks!

**Comment by parssak** [comment]
I'm getting the same error, even after running `yarn add --dev @types/react`

**Comment by db10101** [comment]
Receiving the same error on running next dev server

**Comment by RenaudRohlinger** [comment]
Related:
https://github.com/utsuboco/create-r3f-app/issues/10

@shuta13 Hello! Do you have any idea how to fix the issue?

**Comment by edwinwebb** [comment]
Updating packages to latest after install solved this problem for me.

**Comment by dataTracer1975** [comment]
`yarn upgrade` fixed this problem for me

**Comment by garrettprince** [comment]
echoing @edwinwebb  and @dataTracer1975 here. Updating to packages via `yarn upgrade` worked like a charm. Thanks!

**Comment by RenaudRohlinger** [comment]
#77 should fix the issue. Thanks @shuta13
