### ISSUE TITLE
Disable canvas mouse on dom hover !

### ISSUE THREAD

**Issue by PaganViking** [pmndrs/react-three-next#79]
I have GUI panels on dom where i push and scroll buttons.
But the 3d canvas is moveing and zooming at the same time.
Any ideas ? thanks up front !

**Comment by chasedavis** [comment]
Maybe try to remove [this line](https://github.com/pmndrs/react-three-next/blob/9789f5782a27c1e43c22ee8e886aec3d54604ac7/src/components/layout/canvas.jsx#L34) and also `domElement={dom.current}` on line 22?

**Comment by chasedavis** [comment]
Oh really? 

I think I have the issue you are talking about [here](https://r3f-gradient.vercel.app). When you drag on the generate button for instance it will orbit the camera.

And then [here](https://meshbg-9g84xbt64-chasedavis.vercel.app/), I took my own advice and removed the 2 lines above and dom events are no longer being passed through when you are hovering over the dom, but the camera is not frozen as long as you're hovered over the canvas. Maybe I don't understand your issue fully (and I definitely don't understand the event systems fully! )

I am testing on chrome/macOS.

**Comment by eriksachse** [comment]
I was thinking about this problem as well since I have custom camera controls. I just made a new store value called domhover that I set to true or false with onMouseEnter and onMouseLeave. Then I disable the camera controls depending on that state.
