### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by hyamero** [pmndrs/react-three-next#83]
Template: `yarn create r3f-app next my-app -ts` 

![module-err](https://user-images.githubusercontent.com/78056869/175856840-4c6416b1-3e95-4fe6-a75a-e81e0219771a.png)
`Cannot find module 'module'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?`

tsconfig.json: 
![err-2](https://user-images.githubusercontent.com/78056869/175857048-2a92e72c-7842-4fc1-8196-a423830c7efd.png)
`Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.`

Adding `    "moduleResolution": "node"` in `tsconfig.json` fixes the issue

**Comment by RenaudRohlinger** [comment]
Thanks for the feedback. I added a custom tsconfig for typescript in the CLI: 
https://github.com/utsuboco/create-r3f-app/commit/18152a0f386beb640c6a15a857099b824f315584#diff-c565210742385118748417cad32c9455819f02fa7a07850ffb46ca92dc769beeR96-R119

It would be great if you could try again to see if it fixes your issue.

**Comment by hyamero** [comment]
This fixed the issue, thanks @RenaudRohlinger!
