### ISSUE TITLE
Module parse failed: Unexpected token (1:10) for .frag and .vert files

### ISSUE THREAD

**Issue by westfalensgod** [pmndrs/react-three-next#92]
I tried to run a few times this boilerplate, but encountered the same issue:

![image](https://user-images.githubusercontent.com/24266984/187294790-11c1d952-9aae-42e3-bcf4-fa4949b31117.png)

Looks like there's a problem with the `glslify-loader`, but I can't tell what exactly breaks

![image](https://user-images.githubusercontent.com/24266984/187295087-d7345aca-a9b0-4e3b-939b-d91b58dcbb25.png)

**Comment by westfalensgod** [comment]
I'm closing the issue. The problem was with the old version of node js (apparently, the version I used was 14.13, which is quite old version). Steps that I did:
1. Updated nodejs
2. Installed yarn
3. Followed installation steps from scratch

**Comment by mehrdad-shokri** [comment]
@westfalensgod what version are you using now?
