### ISSUE TITLE
Unhandled Runtime Error TypeError: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by westfalensgod** [pmndrs/react-three-next#93]
There's an error right after running the project for the first time. For some reason, service worker does not work

Unhandled Runtime Error TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/sw.js'): A bad HTTP response code (404) was received when fetching the script.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/24266984/187307714-b1ebdf75-930d-4cae-9720-2075b228129c.png">

**Comment by mehrdad-shokri** [comment]
@westfalensgod I could get it running by removing ``pwa`` from ``KEYS_TO_OMIT`` in ``next.config.js`` the reducer basically ignores any config which it's key exists in ``KEYS_TO_OMIT``. I'm not aware of the reason for this function but as far as I see pwa config is setup in this block and the next reduce basically ignores it. please correct me if I'm wrong.

**Comment by shaolinseed** [comment]
Same issue here, will i run into issues during production if I remove pwa?

**Comment by RenaudRohlinger** [comment]
Thanks!

next-pwa was not up to date with the latest version of nextjs but everything should be fine now:
https://github.com/shadowwalker/next-pwa/commit/1e6af5fa9f6a807930f451adb5ab5078d5cda451#diff-38fcdef48d4c9636b640c40cb75b5278d405ab90f1b0960895900a068436f4cb
