### ISSUE TITLE
Are Babel packages still used?

### ISSUE THREAD

**Issue by kayden1940** [pmndrs/react-three-next#94]
Got a question about babel in this repo.
Reading from there would be an babel.config.js for @babel/plugin-transform-runtime, babel-plugin-glsl. But there isn't one in this repoe, is babel packages not used anymore? or there is some tricks of next.js I am not aware of?
https://nextjs.org/docs/advanced-features/customizing-babel-config

**Comment by RenaudRohlinger** [comment]
@kayden1940 Ah, thanks for the issue after moving to SWC I forgot to remove some babel dependencies. Indeed since Nextjs v11 we moved from babel to SWC so these dependencies are not necessary anymore
