### ISSUE TITLE
Hydration Error

### ISSUE THREAD

**Issue by ariesgun** [pmndrs/react-three-next#97]
I deployed this repository on a digitalocean droplet. Then I executed yarn build and yarn start.

When I accessed the webpage http://.../box, I got the following error.
https://reactjs.org/docs/error-decoder.html/?invariant=423

```
There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

Error from console
```
framework-3583eef75b58b7b2.js:1 TypeError: Cannot redefine property: _currentRenderer
    at Function.defineProperties (<anonymous>)
    at C (568.40a301541589392c.js:1:3694)
    at 568.40a301541589392c.js:1:4509
    at O (568.40a301541589392c.js:1:3574)
    at O (568.40a301541589392c.js:1:3630)
    at O (568.40a301541589392c.js:1:3630)
    at O (568.40a301541589392c.js:1:3630)
    at O (568.40a301541589392c.js:1:3630)
    at O (568.40a301541589392c.js:1:3630)
    at O (568.40a301541589392c.js:1:3630)
```

When I switched to "yarn dev", everything works fine.
Anyone got this issue before? There is no much information from the console. Appreciate for some advices.

**Comment by RenaudRohlinger** [comment]
Probably related to the recent upgrade to its-fine for bridging context. A temporary solution to your case might be to revert to using zustand to bridge the nextjs router context.

**Comment by CodyJasonBennett** [comment]
This is related to https://github.com/pmndrs/react-three-fiber/issues/2533 which was fixed in a recent patch. Try updating R3F or doing a clean install.
