### ISSUE TITLE
Static site builds fail when running with client-side error TypeError: Cannot redefine property: _currentRenderer

### ISSUE THREAD

**Issue by ivyroot** [pmndrs/react-three-next#98]
I took the following steps to build the example site and export it as a static site:

`yarn create r3f-app next my-app` 
`cd my-app`
`npm run-script dev`  ==> site works fine when browsing to localhost:3000
`npm run-script export` then `http-server out`   (after first npm installing http-server globally)

When viewing the page there is a client-side error:

"Application error: a client-side exception has occurred (see the browser console for more information)."

Console output looks like this:
```
framework-3583eef75b58b7b2.js:1 TypeError: Cannot redefine property: _currentRenderer
    at Function.defineProperties (<anonymous>)
```

**Comment by maxsilvauk** [comment]
Yes I also have this problem. When deploying to Vercel it also shows this error message.

Application error: a client-side exception has occurred (see the browser console for more information).

Did you get anywhere with this @ivyroot?

**Comment by maxsilvauk** [comment]
@ivyroot - I would use this instead https://github.com/pmndrs/react-three-next

**Comment by skrichten** [comment]
+1 ... Same issue for me.

**Comment by skrichten** [comment]
Downgrading r3f from ^8.8.4 to 8.7.2 fixed this for me

**Comment by CodyJasonBennett** [comment]
Try updating R3F to latest or upgrading your lockfile and doing a clean install.

**Comment by RenaudRohlinger** [comment]
This issue should be fixed with the latest r3f version thanks @CodyJasonBennett
