### ISSUE TITLE
How to pass props between DOM Page and Three JS Page?

### ISSUE THREAD

**Issue by SaadBazaz** [pmndrs/react-three-next#99]
Hey,
Thanks for the awesome repo. Helped a noob like me get up and running. 

How can I pass bodyColor (as in the example below) from the DOM page to the R3J Page?
<img width="531" alt="Screenshot 2022-10-09 at 3 49 24 PM" src="https://user-images.githubusercontent.com/51885228/194752670-898422f8-bd89-4c8e-9253-39a2f78a07ec.png">

**Comment by pi43r** [comment]
I guess there are multiple solutions to this. I'm not yet familiar with the new syntax of `Page.r3f` and how to do prop drilling there.
But another way would be to use the [zustand](https://github.com/pmndrs/zustand) store that comes with react-three-next. You would add your variable to the [store.js](https://github.com/pmndrs/react-three-next/blob/3848c8857f38ea3611173bb0feabe98b0ee0cc39/src/helpers/store.js#L6)
and retrieve and write like this 
```js
// retrieve
const bodyColor = useStore( (store) => store.yourVar )

// write
useStore.setState( { yourVar: bodyColor } )
```

**Comment by SaadBazaz** [comment]
This seems like a long way to solve a simple problem. I ended up using [r3f-next-starter](https://github.com/whoisryosuke/r3f-next-starter) and it works great!
